spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: gzhmt
    password: rj17208zhl
    url: jdbc:mysql://localhost:3306/mealtime?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true

server:
  context-path: /mealtime
#logging:
#  pattern:
#    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
#  file: g:/logger.txt
#  path: g:/